import type { Metadata } from 'next';
import { Exo_2 } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { ClerkProvider } from '@clerk/nextjs';
import Providers from './providers';

const exo = Exo_2({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Wardrobee',
  description: 'Demo e-commerce project generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${exo.className} min-h-screen bg-background text-foreground`}
        >
          <Providers>
            <Navbar />
            <main>{children}</main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
